In [21]:
import numpy as np
arr = np.random.randint(0, 11, (3, 3))
arr_sum = np.sum(arr)
arr_mean = np.mean(arr)
arr_std = np.std(arr)
print("Array:\n", arr)
print("Sum:", arr_sum)
print("Mean:", arr_mean)
print("Standard Deviation:", arr_std)


Array:
 [[ 9  3  0]
 [ 1  3  4]
 [ 1 10  3]]
Sum: 34
Mean: 3.7777777777777777
Standard Deviation: 3.292340531117567


In [3]:
arr = np.random.randint(1, 10, 10)  
cumsum_arr = np.cumsum(arr)  
print(arr)  
print("Cumulative Sum:", cumsum_arr)


[7 4 6 3 6 8 9 2 7 4]
Cumulative Sum: [ 7 11 17 20 26 34 43 45 52 56]


In [9]:
A = np.random.randint(1, 10, (2, 3))
B = np.random.randint(1, 10, (2, 3))
add = A + B
sub = A - B
mul = A * B
div = A / B
print("Array A:\n", A)
print("Array B:\n", B)
print("Addition:\n", add)
print("Subtraction:\n", sub)
print("Multiplication:\n", mul)
print("Division:\n", div)

Array A:
 [[4 8 1]
 [6 8 8]]
Array B:
 [[9 9 5]
 [5 2 6]]
Addition:
 [[13 17  6]
 [11 10 14]]
Subtraction:
 [[-5 -1 -4]
 [ 1  6  2]]
Multiplication:
 [[36 72  5]
 [30 16 48]]
Division:
 [[0.44444444 0.88888889 0.2       ]
 [1.2        4.         1.33333333]]


In [11]:
identity_matrix = np.eye(4)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
a = np.array([5, 10, 15, 20, 25])
result = a / 5
print(result)


[1. 2. 3. 4. 5.]


In [15]:
arr = np.arange(1, 13)
reshaped_arr = arr.reshape(3, 4)
print(reshaped_arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
matrix = np.random.randint(1, 10, (3, 3))
flattened = matrix.flatten()
print("Original Matrix:\n", matrix)
print("Flattened Array:", flattened)


Original Matrix:
 [[1 9 5]
 [2 4 1]
 [2 8 5]]
Flattened Array: [1 9 5 2 4 1 2 8 5]


In [19]:
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))
h_stack = np.hstack((A, B))
v_stack = np.vstack((A, B))
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Horizontally Stacked:\n", h_stack)
print("Vertically Stacked:\n", v_stack)


Matrix A:
 [[2 1 3]
 [8 7 7]
 [7 7 5]]
Matrix B:
 [[1 2 3]
 [3 9 5]
 [1 1 3]]
Horizontally Stacked:
 [[2 1 3 1 2 3]
 [8 7 7 3 9 5]
 [7 7 5 1 1 3]]
Vertically Stacked:
 [[2 1 3]
 [8 7 7]
 [7 7 5]
 [1 2 3]
 [3 9 5]
 [1 1 3]]


In [27]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6, 7])
concatenated = np.concatenate((arr1, arr2))
print(concatenated)


[1 2 3 4 5 6 7]


In [29]:
matrix = np.random.randint(1, 10, (3, 2))
transposed = matrix.T
reshaped = transposed.reshape(3, 2)
print("Original Matrix:\n", matrix)
print("Transposed Matrix:\n", transposed)
print("Reshaped Matrix:\n", reshaped)


Original Matrix:
 [[4 3]
 [2 7]
 [9 7]]
Transposed Matrix:
 [[4 2 9]
 [3 7 7]]
Reshaped Matrix:
 [[4 2]
 [9 3]
 [7 7]]


In [31]:
arr = np.arange(1, 16)
extracted = arr[2:11:2]
print("Original Array:", arr)
print("Extracted Elements:", extracted)


Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Extracted Elements: [ 3  5  7  9 11]


In [33]:
matrix = np.random.randint(1, 10, (5, 5))
sub_matrix = matrix[1:4, 2:5]
print("Original Matrix:\n", matrix)
print("Extracted Sub-Matrix:\n", sub_matrix)


Original Matrix:
 [[1 9 5 4 9]
 [4 6 9 9 8]
 [5 7 3 1 4]
 [2 5 4 8 8]
 [8 9 7 9 3]]
Extracted Sub-Matrix:
 [[9 9 8]
 [3 1 4]
 [4 8 8]]


In [35]:
arr = np.random.randint(5, 20, 10)
arr[arr > 10] = 10
print("Modified Array:", arr)


Modified Array: [10  9 10 10  6 10  6 10 10  7]


In [37]:
arr = np.arange(10)
selected_elements = arr[[0, 2, 4, 6]]
print("Original Array:", arr)
print("Selected Elements:", selected_elements)


Original Array: [0 1 2 3 4 5 6 7 8 9]
Selected Elements: [0 2 4 6]


In [39]:
arr = np.arange(10)
reversed_arr = arr[::-1]
print("Original Array:", arr)
print("Reversed Array:", reversed_arr)


Original Array: [0 1 2 3 4 5 6 7 8 9]
Reversed Array: [9 8 7 6 5 4 3 2 1 0]


In [41]:
matrix = np.random.randint(1, 10, (3, 3))
row_vector = np.array([1, 2, 3])
result = matrix + row_vector
print("Original Matrix:\n", matrix)
print("Row Vector:", row_vector)
print("Result After Broadcasting:\n", result)


Original Matrix:
 [[7 5 9]
 [6 3 2]
 [9 9 5]]
Row Vector: [1 2 3]
Result After Broadcasting:
 [[ 8  7 12]
 [ 7  5  5]
 [10 11  8]]


In [43]:
arr = np.array([2, 4, 6, 8, 10])
scalar = 3
result = arr * scalar
print("Original Array:", arr)
print("Scalar Value:", scalar)
print("Result After Broadcasting:", result)


Original Array: [ 2  4  6  8 10]
Scalar Value: 3
Result After Broadcasting: [ 6 12 18 24 30]


In [45]:
matrix = np.random.randint(1, 10, (3, 3))
column_vector = np.array([[1], [2], [3]])
result = matrix - column_vector
print("Original Matrix:\n", matrix)
print("Column Vector:\n", column_vector)
print("Result After Broadcasting:\n", result)


Original Matrix:
 [[7 5 2]
 [8 3 9]
 [3 5 1]]
Column Vector:
 [[1]
 [2]
 [3]]
Result After Broadcasting:
 [[ 6  4  1]
 [ 6  1  7]
 [ 0  2 -2]]


In [47]:
array_3d = np.random.randint(1, 10, (2, 3, 3))
scalar = 5
result = array_3d + scalar
print("Original 3D Array:\n", array_3d)
print("Scalar Value:", scalar)
print("Result After Broadcasting:\n", result)


Original 3D Array:
 [[[2 5 3]
  [3 6 9]
  [6 3 9]]

 [[5 1 7]
  [2 5 5]
  [1 8 1]]]
Scalar Value: 5
Result After Broadcasting:
 [[[ 7 10  8]
  [ 8 11 14]
  [11  8 14]]

 [[10  6 12]
  [ 7 10 10]
  [ 6 13  6]]]


In [49]:
arr1 = np.arange(1, 5).reshape(4, 1)
arr2 = np.arange(1, 6).reshape(1, 5)
result = arr1 + arr2
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Result After Broadcasting:\n", result)


Array 1:
 [[1]
 [2]
 [3]
 [4]]
Array 2:
 [[1 2 3 4 5]]
Result After Broadcasting:
 [[2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]]


In [51]:
matrix = np.random.randint(1, 20, (3, 3))
sqrt_matrix = np.sqrt(matrix)
print("Original Matrix:\n", matrix)
print("Square Root Matrix:\n", sqrt_matrix)


Original Matrix:
 [[15 13 13]
 [13 15  8]
 [19  3 16]]
Square Root Matrix:
 [[3.87298335 3.60555128 3.60555128]
 [3.60555128 3.87298335 2.82842712]
 [4.35889894 1.73205081 4.        ]]


In [53]:
arr1 = np.random.randint(1, 10, 5)
arr2 = np.random.randint(1, 10, 5)
dot_product = np.dot(arr1, arr2)
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Dot Product:", dot_product)


Array 1: [1 2 5 7 1]
Array 2: [4 2 7 1 4]
Dot Product: 54


In [55]:
arr1 = np.random.randint(1, 20, 5)
arr2 = np.random.randint(1, 20, 5)
comparison = arr1 > arr2
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Comparison Result (arr1 > arr2):", comparison)


Array 1: [12 13 18  9 13]
Array 2: [18 19  6  4 19]
Comparison Result (arr1 > arr2): [False False  True  True False]


In [57]:
matrix = np.random.randint(1, 10, (3, 3))
doubled_matrix = matrix * 2
print("Original Matrix:\n", matrix)
print("Doubled Matrix:\n", doubled_matrix)


Original Matrix:
 [[2 9 6]
 [9 3 5]
 [8 9 7]]
Doubled Matrix:
 [[ 4 18 12]
 [18  6 10]
 [16 18 14]]


In [59]:
arr = np.random.randint(1, 100, 100)
even_sum = np.sum(arr[arr % 2 == 0])
print("Original Array:", arr)
print("Sum of Even Numbers:", even_sum)


Original Array: [31 82 80 31 39 10 11 11 77  6 41 80 24 38 84 22 31 24 89 82 25  1 89 35
 88 86 31 64 45 98 57 41 83 99  8 70 64 16 26 18 47 25 83 20 25 47 61 79
 52 85 66 94 70 40 65  9 65 95 25 80  1 74 49 61 49 92 21 70  4 83 16 62
 45 44  3 10 80 78 29 32 25 35 14 49 84 22 87 85 72 10 97 69  7 68 37 20
 67 78 88 84]
Sum of Even Numbers: 2594


In [61]:
matrix = np.random.randint(1, 10, (3, 3))
determinant = np.linalg.det(matrix)
print("Matrix:\n", matrix)
print("Determinant:", determinant)


Matrix:
 [[5 3 2]
 [5 7 9]
 [5 9 6]]
Determinant: -129.99999999999997


In [63]:
matrix = np.random.randint(1, 10, (2, 2))
if np.linalg.det(matrix) != 0:
    inverse_matrix = np.linalg.inv(matrix)
    identity_matrix = np.round(np.dot(matrix, inverse_matrix), decimals=6)
    print("Original Matrix:\n", matrix)
    print("Inverse Matrix:\n", inverse_matrix)
    print("Verification (Original * Inverse):\n", identity_matrix)
else:
    print("Matrix is singular and cannot be inverted.")


Original Matrix:
 [[9 7]
 [1 2]]
Inverse Matrix:
 [[ 0.18181818 -0.63636364]
 [-0.09090909  0.81818182]]
Verification (Original * Inverse):
 [[1. 0.]
 [0. 1.]]


In [65]:
matrix = np.random.randint(1, 10, (2, 2))
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Matrix:\n", matrix)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Matrix:
 [[1 7]
 [8 7]]
Eigenvalues:
 [-4.06225775 12.06225775]
Eigenvectors:
 [[-0.81031082 -0.53471965]
 [ 0.58600032 -0.84502952]]


In [67]:
A = np.array([[2, 3], [4, 6]])
B = np.array([5, 10])
if np.linalg.det(A) != 0:
    solution = np.linalg.solve(A, B)
    print("Solution (x, y):", solution)
else:
    print("The system has no unique solution (singular matrix).")


The system has no unique solution (singular matrix).


In [69]:
matrix = np.random.randint(1, 10, (3, 3))
U, S, Vt = np.linalg.svd(matrix)
S_matrix = np.diag(S)
reconstructed_matrix = U @ S_matrix @ Vt
print("Original Matrix:\n", matrix)
print("U Matrix:\n", U)
print("Singular Values:\n", S)
print("V Transpose Matrix:\n", Vt)
print("Reconstructed Matrix:\n", np.round(reconstructed_matrix, decimals=6))


Original Matrix:
 [[9 4 4]
 [7 2 1]
 [9 6 2]]
U Matrix:
 [[-0.62820274  0.54270806  0.55752065]
 [-0.42800384  0.35735509 -0.83012652]
 [-0.6497492  -0.76010874  0.00778968]]
Singular Values:
 [16.76228953  2.02950499  1.70492207]
V Transpose Matrix:
 [[-0.86489345 -0.43355139 -0.25296743]
 [ 0.26847903 -0.82537862  0.49665798]
 [-0.42412066  0.36163979  0.83026401]]
Reconstructed Matrix:
 [[9. 4. 4.]
 [7. 2. 1.]
 [9. 6. 2.]]
